{
    'name': 'Tutorial project',
    'version': '18.0.10.0',
    'summary': 'Tutorial project for Odoo development learning',
    'sequence': -100,
    'description': """This module is a tutorial project designed to help users learn Odoo development. It provides a basic structure and examples of how to create and manage Odoo modules.""",
    'category': 'for study purpose',
    'website': 'https://www.odoo.com',
    'depends': ['base','product','mail','sale'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/mail_template.xml',
        'wizard/staff_wizard_view.xml',
        'wizard/excel_wizard_view.xml',
        'views/staff_view.xml',
        'views/menu_view.xml',
        'views/sale_order_view.xml',
        'reports/staff_report.xml'
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'images': ['static/description/icon.png'],
}
