from . import exam_planning
from . import student_registration
from . import student_exam_assignment
from . import exam_hall
from . import exam_seating
from . import exam_dashboard
from . import exam_conducting
from . import exam_result
from . import exam_subject
